//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#loom
////
//// DO NOT EDIT THIS FILE DIRECTLY. Instead, edit the
//// corresponding .loom.html template file and run `./glimr
//// loom:compile`.
////

import database/main/models/weight_type/gen/weight_type.{type WeightType}
import glimr/loom/runtime

pub fn render(weight_type weight_type: WeightType) -> String {
  "" <> "\n<div>" <> runtime.display(weight_type.name) <> "</div>\n\n"
}
