-- Generated by Glimr ✨ (sqlite)

CREATE TABLE exercises (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE UNIQUE INDEX idx_exercises_name ON exercises (name);
