-- Generated by Glimr ✨ (sqlite)

CREATE TABLE workouts (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  exercise_id INTEGER NOT NULL,
  weight_type_id INTEGER NOT NULL,
  weight INTEGER NOT NULL,
  reps INTEGER NOT NULL,
  notes TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
