-- Generated by Glimr

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    payload TEXT NOT NULL,
    last_activity INTEGER NOT NULL
);

-- Index for faster garbage collection lookups
CREATE INDEX IF NOT EXISTS idx_sessions_last_activity ON sessions (last_activity);
